version: '3.4'

services:
  bookeurekaserver:
    image: bookeurekaserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9999:9999
    networks:
      - bookstore-network
    

  bookserver:
    image: bookserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://bookeurekaserver:9999/eureka
    ports:
      - 9090:9090
    networks:
      - bookstore-network  
   
     
  bookclient:
    image: bookclient
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://bookeurekaserver:9999/eureka
    ports:
      - 9091:9091
    networks:
      - bookstore-network  
    depends_on:
      - bookserver

networks:
  bookstore-network: